<?php
/** 
 * Nimbus - Manage, Share & Collaborate
 *
 * Nimbus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * see LICENSE for more Copyright goodness.
 *
 * @package:		Nimbus
 * @copyright:		2009-2010, Nimbus Dev Group, All rights reserved.
 * @license:		GNU/GPLv3, see LICENSE
 * @version:		1.0.0 Alpha
 */
/**
 * @ignore
 *   This file contains functions and definitions used throughout the Nimbus
 *   system. Please do not edit this file to prevent System breakdown.
 */
/**
 * Function to check compatibility for the environment
 *
 * @access	public
 */
function checkCompatibility(){
	$incompatibilities = array();
	$missing = array();
	
	/**
	 * Check PHP environment
	 */
	if (!version_compare(PHP_VERSION, '5.3', '>=')) {
		$incompatibilities[] = array('Nimbus requires PHP 5.3 or later to run properly.', '000A');
	}
	if (!extension_loaded('sqlite') && !extension_loaded('pdo_sqlite')) {
		$incompatibilities[] = array('Your PHP configuration should support PDO/Sqlite.', '001A');
	}
	if ((!is_writable('/../.nimbus') && !is_readable('/../.nimbus')) && (!is_writable('../nimbus') && !is_readable('../nimbus'))) {
		$incompatibilities[] = array('Your Installation folder and the .nimbus data folder should have at least 0755 permission to work properly.', '002A');
	}
	if (!ini_get('file_uploads')) {
		$incompatibilities[] = array('Your PHP configuration should support file uploads.', '003A');
	}
	
	/**
	 * Check for Optional Extensions
	 */
	if (!extension_loaded('mbstring')) {
		$missing[] = array('MBSTRING support not detected. MBSTRING will be used along with UTF-8 encoding.', '000B');
	}
	if (!extension_loaded('ftp')) {
		$missing[] = array('FTP support not detected. FTP will be used by most project management programs.', '001B');
	}
	if (!extension_loaded('json')) {
		$missing[] = array('JSON support not detected. JSON will be used by nimbus internal and external API calls.', '002B');
	}
	if (!extension_loaded('soap')) {
		$missing[] = array('SOAP support not detected. SOAP will be used by most project management programs.', '003B');
	}
	if (!extension_loaded('xml') && !extension_loaded('xmlreader') && !extension_loaded('xmlwriter')) {
		$missing[] = array('XML support not detected. XML is the most common way of transport, Applications might use this feature.', '004B');
	}
	if (!extension_loaded('xmlrpc')) {
		$missing[] = array('XMLRPC support not detected. XMLRPC will be used by most project management programs.', '005B');
	}
	if (!extension_loaded('zip')) {
		$missing[] = array('ZIP support not detected. File archiving will not be available.', '006B');
	}
	if (!extension_loaded('zlib')) {
		$missing[] = array('ZLIB support not detected. GZIP comperssion will not be available.', '007B');
	}
	if (!function_exists('mail')) {
		$missing[] = array('Native Mail function disabled.', '008B');
	}
	
	/**
	 * End the application when an incompatibility has been determined
	 */
	if (!empty($incompatibilities)) {
		include SYSTEM_DIR . 'shell' . DS . 'common' . DS . 'compatibility.html';
		exit;
	}
}

?>